// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  username: __t.string().primaryKey(),
  pinHash: __t.string().name("pin_hash"),
  salt: __t.string(),
  identity: __t.identity(),
  name: __t.string(),
  color: __t.u32(),
  build: __t.u8(),
  hood: __t.u8(),
  marking: __t.u8(),
  emissiveIntensity: __t.f32().name("emissive_intensity"),
  height: __t.f32(),
  created: __t.timestamp(),
});
