// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sender: __t.identity(),
  senderName: __t.string().name("sender_name"),
  senderColor: __t.u32().name("sender_color"),
  text: __t.string(),
  roomId: __t.u64().name("room_id"),
  createdAt: __t.timestamp().name("created_at"),
});
