// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  color: __t.u32(),
  x: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  roomId: __t.u64().name("room_id"),
  state: __t.string(),
  carryingAnchorId: __t.option(__t.u64()).name("carrying_anchor_id"),
  lastSeen: __t.timestamp().name("last_seen"),
});
