// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AbsorbReducer from "../absorb_reducer";
import ClaimWardenReducer from "../claim_warden_reducer";
import MovePlayerReducer from "../move_player_reducer";
import PickupAnchorReducer from "../pickup_anchor_reducer";
import PlaceAnchorReducer from "../place_anchor_reducer";
import RescueReducer from "../rescue_reducer";
import SealCorridorReducer from "../seal_corridor_reducer";
import SendChatReducer from "../send_chat_reducer";
import SetNameReducer from "../set_name_reducer";
import SpawnLureReducer from "../spawn_lure_reducer";
import StartMatchReducer from "../start_match_reducer";
import WardenActReducer from "../warden_act_reducer";
import WardenMimicReducer from "../warden_mimic_reducer";

export type AbsorbParams = __Infer<typeof AbsorbReducer>;
export type ClaimWardenParams = __Infer<typeof ClaimWardenReducer>;
export type MovePlayerParams = __Infer<typeof MovePlayerReducer>;
export type PickupAnchorParams = __Infer<typeof PickupAnchorReducer>;
export type PlaceAnchorParams = __Infer<typeof PlaceAnchorReducer>;
export type RescueParams = __Infer<typeof RescueReducer>;
export type SealCorridorParams = __Infer<typeof SealCorridorReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SpawnLureParams = __Infer<typeof SpawnLureReducer>;
export type StartMatchParams = __Infer<typeof StartMatchReducer>;
export type WardenActParams = __Infer<typeof WardenActReducer>;
export type WardenMimicParams = __Infer<typeof WardenMimicReducer>;

