// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AbsorbReducer from "../absorb_reducer";
import ClaimWardenReducer from "../claim_warden_reducer";
import CreateMatchReducer from "../create_match_reducer";
import CreatePartyReducer from "../create_party_reducer";
import EarnResidueReducer from "../earn_residue_reducer";
import GrantUnlockReducer from "../grant_unlock_reducer";
import HeartbeatPresenceReducer from "../heartbeat_presence_reducer";
import JoinMatchReducer from "../join_match_reducer";
import JoinPartyByCodeReducer from "../join_party_by_code_reducer";
import KickPartyMemberReducer from "../kick_party_member_reducer";
import LeaveMatchReducer from "../leave_match_reducer";
import LeavePartyReducer from "../leave_party_reducer";
import LockAnchorSlotReducer from "../lock_anchor_slot_reducer";
import LoginAccountReducer from "../login_account_reducer";
import MovePlayerReducer from "../move_player_reducer";
import PartyQueueReducer from "../party_queue_reducer";
import PickupAnchorReducer from "../pickup_anchor_reducer";
import PlaceAnchorReducer from "../place_anchor_reducer";
import RegisterAccountReducer from "../register_account_reducer";
import RescueReducer from "../rescue_reducer";
import SendChatReducer from "../send_chat_reducer";
import SetAvatarReducer from "../set_avatar_reducer";
import SetNameReducer from "../set_name_reducer";
import SetPartyReadyReducer from "../set_party_ready_reducer";
import SetWardenPresentReducer from "../set_warden_present_reducer";
import SpendResidueReducer from "../spend_residue_reducer";
import StartMatchReducer from "../start_match_reducer";
import WardenActReducer from "../warden_act_reducer";
import WardenCorruptAnchorReducer from "../warden_corrupt_anchor_reducer";
import WardenEventReducer from "../warden_event_reducer";
import WardenHeartbeatReducer from "../warden_heartbeat_reducer";
import WardenMimicReducer from "../warden_mimic_reducer";
import WardenSpawnLureReducer from "../warden_spawn_lure_reducer";
import WriteAbsorptionReportReducer from "../write_absorption_report_reducer";

export type AbsorbParams = __Infer<typeof AbsorbReducer>;
export type ClaimWardenParams = __Infer<typeof ClaimWardenReducer>;
export type CreateMatchParams = __Infer<typeof CreateMatchReducer>;
export type CreatePartyParams = __Infer<typeof CreatePartyReducer>;
export type EarnResidueParams = __Infer<typeof EarnResidueReducer>;
export type GrantUnlockParams = __Infer<typeof GrantUnlockReducer>;
export type HeartbeatPresenceParams = __Infer<typeof HeartbeatPresenceReducer>;
export type JoinMatchParams = __Infer<typeof JoinMatchReducer>;
export type JoinPartyByCodeParams = __Infer<typeof JoinPartyByCodeReducer>;
export type KickPartyMemberParams = __Infer<typeof KickPartyMemberReducer>;
export type LeaveMatchParams = __Infer<typeof LeaveMatchReducer>;
export type LeavePartyParams = __Infer<typeof LeavePartyReducer>;
export type LockAnchorSlotParams = __Infer<typeof LockAnchorSlotReducer>;
export type LoginAccountParams = __Infer<typeof LoginAccountReducer>;
export type MovePlayerParams = __Infer<typeof MovePlayerReducer>;
export type PartyQueueParams = __Infer<typeof PartyQueueReducer>;
export type PickupAnchorParams = __Infer<typeof PickupAnchorReducer>;
export type PlaceAnchorParams = __Infer<typeof PlaceAnchorReducer>;
export type RegisterAccountParams = __Infer<typeof RegisterAccountReducer>;
export type RescueParams = __Infer<typeof RescueReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SetAvatarParams = __Infer<typeof SetAvatarReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetPartyReadyParams = __Infer<typeof SetPartyReadyReducer>;
export type SetWardenPresentParams = __Infer<typeof SetWardenPresentReducer>;
export type SpendResidueParams = __Infer<typeof SpendResidueReducer>;
export type StartMatchParams = __Infer<typeof StartMatchReducer>;
export type WardenActParams = __Infer<typeof WardenActReducer>;
export type WardenCorruptAnchorParams = __Infer<typeof WardenCorruptAnchorReducer>;
export type WardenEventParams = __Infer<typeof WardenEventReducer>;
export type WardenHeartbeatParams = __Infer<typeof WardenHeartbeatReducer>;
export type WardenMimicParams = __Infer<typeof WardenMimicReducer>;
export type WardenSpawnLureParams = __Infer<typeof WardenSpawnLureReducer>;
export type WriteAbsorptionReportParams = __Infer<typeof WriteAbsorptionReportReducer>;

