// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  code: __t.string(),
  state: __t.string(),
  timeLeft: __t.f32().name("time_left"),
  phase: __t.u8(),
  anchorsPlaced: __t.u8().name("anchors_placed"),
  exitOpen: __t.bool().name("exit_open"),
  wardenIdentity: __t.option(__t.identity()).name("warden_identity"),
  wardenLastAction: __t.timestamp().name("warden_last_action"),
  createdAt: __t.timestamp().name("created_at"),
});
