// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.4.0 (commit b3547448cf06d65c5133e884c9a24f126f92eb12).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AbsorbReducer from "./absorb_reducer";
import ClaimWardenReducer from "./claim_warden_reducer";
import CreateMatchReducer from "./create_match_reducer";
import CreatePartyReducer from "./create_party_reducer";
import EarnResidueReducer from "./earn_residue_reducer";
import GrantUnlockReducer from "./grant_unlock_reducer";
import HeartbeatPresenceReducer from "./heartbeat_presence_reducer";
import JoinMatchReducer from "./join_match_reducer";
import JoinPartyByCodeReducer from "./join_party_by_code_reducer";
import KickPartyMemberReducer from "./kick_party_member_reducer";
import LeaveMatchReducer from "./leave_match_reducer";
import LeavePartyReducer from "./leave_party_reducer";
import LockAnchorSlotReducer from "./lock_anchor_slot_reducer";
import LoginAccountReducer from "./login_account_reducer";
import MovePlayerReducer from "./move_player_reducer";
import PartyQueueReducer from "./party_queue_reducer";
import PickupAnchorReducer from "./pickup_anchor_reducer";
import PlaceAnchorReducer from "./place_anchor_reducer";
import RegisterAccountReducer from "./register_account_reducer";
import RescueReducer from "./rescue_reducer";
import SendChatReducer from "./send_chat_reducer";
import SetAvatarReducer from "./set_avatar_reducer";
import SetNameReducer from "./set_name_reducer";
import SetPartyReadyReducer from "./set_party_ready_reducer";
import SetWardenPresentReducer from "./set_warden_present_reducer";
import SpendResidueReducer from "./spend_residue_reducer";
import StartMatchReducer from "./start_match_reducer";
import WardenActReducer from "./warden_act_reducer";
import WardenCorruptAnchorReducer from "./warden_corrupt_anchor_reducer";
import WardenEventReducer from "./warden_event_reducer";
import WardenHeartbeatReducer from "./warden_heartbeat_reducer";
import WardenMimicReducer from "./warden_mimic_reducer";
import WardenSpawnLureReducer from "./warden_spawn_lure_reducer";
import WriteAbsorptionReportReducer from "./write_absorption_report_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AbsorptionReportRow from "./absorption_report_table";
import AccountRow from "./account_table";
import AnchorRow from "./anchor_table";
import AnchorAssignmentRow from "./anchor_assignment_table";
import AvatarDoneRow from "./avatar_done_table";
import ChatMessageRow from "./chat_message_table";
import GameMatchRow from "./game_match_table";
import PartyRow from "./party_table";
import PartyMemberRow from "./party_member_table";
import PlayerRow from "./player_table";
import ProgressionRow from "./progression_table";
import TetherRow from "./tether_table";
import UnlockRow from "./unlock_table";
import WalletRow from "./wallet_table";
import WardenPresentRow from "./warden_present_table";
import WorldEventRow from "./world_event_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  absorption_report: __table({
    name: 'absorption_report',
    indexes: [
      { accessor: 'id', name: 'absorption_report_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'match_id', name: 'absorption_report_match_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
      ] },
    ],
    constraints: [
      { name: 'absorption_report_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AbsorptionReportRow),
  account: __table({
    name: 'account',
    indexes: [
      { accessor: 'identity', name: 'account_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'username', name: 'account_username_idx_btree', algorithm: 'btree', columns: [
        'username',
      ] },
    ],
    constraints: [
      { name: 'account_username_key', constraint: 'unique', columns: ['username'] },
    ],
  }, AccountRow),
  anchor: __table({
    name: 'anchor',
    indexes: [
      { accessor: 'id', name: 'anchor_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'match_id', name: 'anchor_match_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
      ] },
    ],
    constraints: [
      { name: 'anchor_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AnchorRow),
  anchor_assignment: __table({
    name: 'anchor_assignment',
    indexes: [
      { accessor: 'id', name: 'anchor_assignment_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'match_id', name: 'anchor_assignment_match_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
      ] },
    ],
    constraints: [
      { name: 'anchor_assignment_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AnchorAssignmentRow),
  avatar_done: __table({
    name: 'avatar_done',
    indexes: [
      { accessor: 'identity', name: 'avatar_done_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'avatar_done_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, AvatarDoneRow),
  chat_message: __table({
    name: 'chat_message',
    indexes: [
      { accessor: 'id', name: 'chat_message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'match_id', name: 'chat_message_match_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
      ] },
    ],
    constraints: [
      { name: 'chat_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatMessageRow),
  game_match: __table({
    name: 'game_match',
    indexes: [
      { accessor: 'id', name: 'game_match_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'game_match_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameMatchRow),
  party: __table({
    name: 'party',
    indexes: [
      { accessor: 'id', name: 'party_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'party_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PartyRow),
  party_member: __table({
    name: 'party_member',
    indexes: [
      { accessor: 'id', name: 'party_member_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'member', name: 'party_member_member_idx_btree', algorithm: 'btree', columns: [
        'member',
      ] },
      { accessor: 'party_id', name: 'party_member_party_id_idx_btree', algorithm: 'btree', columns: [
        'partyId',
      ] },
    ],
    constraints: [
      { name: 'party_member_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PartyMemberRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'match_id', name: 'player_match_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
      ] },
    ],
    constraints: [
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  progression: __table({
    name: 'progression',
    indexes: [
      { accessor: 'username', name: 'progression_username_idx_btree', algorithm: 'btree', columns: [
        'username',
      ] },
    ],
    constraints: [
      { name: 'progression_username_key', constraint: 'unique', columns: ['username'] },
    ],
  }, ProgressionRow),
  tether: __table({
    name: 'tether',
    indexes: [
      { accessor: 'id', name: 'tether_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'match_id', name: 'tether_match_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
      ] },
    ],
    constraints: [
      { name: 'tether_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TetherRow),
  unlock: __table({
    name: 'unlock',
    indexes: [
      { accessor: 'id', name: 'unlock_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'username', name: 'unlock_username_idx_btree', algorithm: 'btree', columns: [
        'username',
      ] },
    ],
    constraints: [
      { name: 'unlock_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UnlockRow),
  wallet: __table({
    name: 'wallet',
    indexes: [
      { accessor: 'username', name: 'wallet_username_idx_btree', algorithm: 'btree', columns: [
        'username',
      ] },
    ],
    constraints: [
      { name: 'wallet_username_key', constraint: 'unique', columns: ['username'] },
    ],
  }, WalletRow),
  warden_present: __table({
    name: 'warden_present',
    indexes: [
      { accessor: 'id', name: 'warden_present_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'warden_present_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WardenPresentRow),
  world_event: __table({
    name: 'world_event',
    indexes: [
      { accessor: 'id', name: 'world_event_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'match_id', name: 'world_event_match_id_idx_btree', algorithm: 'btree', columns: [
        'matchId',
      ] },
    ],
    constraints: [
      { name: 'world_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldEventRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("absorb", AbsorbReducer),
  __reducerSchema("claim_warden", ClaimWardenReducer),
  __reducerSchema("create_match", CreateMatchReducer),
  __reducerSchema("create_party", CreatePartyReducer),
  __reducerSchema("earn_residue", EarnResidueReducer),
  __reducerSchema("grant_unlock", GrantUnlockReducer),
  __reducerSchema("heartbeat_presence", HeartbeatPresenceReducer),
  __reducerSchema("join_match", JoinMatchReducer),
  __reducerSchema("join_party_by_code", JoinPartyByCodeReducer),
  __reducerSchema("kick_party_member", KickPartyMemberReducer),
  __reducerSchema("leave_match", LeaveMatchReducer),
  __reducerSchema("leave_party", LeavePartyReducer),
  __reducerSchema("lock_anchor_slot", LockAnchorSlotReducer),
  __reducerSchema("login_account", LoginAccountReducer),
  __reducerSchema("move_player", MovePlayerReducer),
  __reducerSchema("party_queue", PartyQueueReducer),
  __reducerSchema("pickup_anchor", PickupAnchorReducer),
  __reducerSchema("place_anchor", PlaceAnchorReducer),
  __reducerSchema("register_account", RegisterAccountReducer),
  __reducerSchema("rescue", RescueReducer),
  __reducerSchema("send_chat", SendChatReducer),
  __reducerSchema("set_avatar", SetAvatarReducer),
  __reducerSchema("set_name", SetNameReducer),
  __reducerSchema("set_party_ready", SetPartyReadyReducer),
  __reducerSchema("set_warden_present", SetWardenPresentReducer),
  __reducerSchema("spend_residue", SpendResidueReducer),
  __reducerSchema("start_match", StartMatchReducer),
  __reducerSchema("warden_act", WardenActReducer),
  __reducerSchema("warden_corrupt_anchor", WardenCorruptAnchorReducer),
  __reducerSchema("warden_event", WardenEventReducer),
  __reducerSchema("warden_heartbeat", WardenHeartbeatReducer),
  __reducerSchema("warden_mimic", WardenMimicReducer),
  __reducerSchema("warden_spawn_lure", WardenSpawnLureReducer),
  __reducerSchema("write_absorption_report", WriteAbsorptionReportReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.4.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

