// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AbsorptionReport = __t.object("AbsorptionReport", {
  id: __t.u64(),
  matchId: __t.u64(),
  username: __t.string(),
  felt: __t.string(),
  truth: __t.string(),
  createdAt: __t.timestamp(),
});
export type AbsorptionReport = __Infer<typeof AbsorptionReport>;

export const Account = __t.object("Account", {
  username: __t.string(),
  pinHash: __t.string(),
  salt: __t.string(),
  identity: __t.identity(),
  name: __t.string(),
  color: __t.u32(),
  build: __t.u8(),
  hood: __t.u8(),
  marking: __t.u8(),
  emissiveIntensity: __t.f32(),
  height: __t.f32(),
  created: __t.timestamp(),
});
export type Account = __Infer<typeof Account>;

export const Anchor = __t.object("Anchor", {
  id: __t.u64(),
  matchId: __t.u64(),
  kind: __t.string(),
  x: __t.f32(),
  z: __t.f32(),
  carriedBy: __t.option(__t.identity()),
  placed: __t.bool(),
});
export type Anchor = __Infer<typeof Anchor>;

export const AnchorAssignment = __t.object("AnchorAssignment", {
  id: __t.u64(),
  matchId: __t.u64(),
  slot: __t.u8(),
  carrier: __t.identity(),
  locked: __t.bool(),
  createdAt: __t.timestamp(),
});
export type AnchorAssignment = __Infer<typeof AnchorAssignment>;

export const AvatarDone = __t.object("AvatarDone", {
  identity: __t.identity(),
});
export type AvatarDone = __Infer<typeof AvatarDone>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  matchId: __t.u64(),
  sender: __t.identity(),
  senderName: __t.string(),
  senderColor: __t.u32(),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const GameMatch = __t.object("GameMatch", {
  id: __t.u64(),
  code: __t.string(),
  state: __t.string(),
  timeLeft: __t.f32(),
  phase: __t.u8(),
  anchorsPlaced: __t.u8(),
  exitOpen: __t.bool(),
  wardenIdentity: __t.option(__t.identity()),
  wardenLastAction: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type GameMatch = __Infer<typeof GameMatch>;

export const Party = __t.object("Party", {
  id: __t.u64(),
  code: __t.string(),
  leader: __t.identity(),
  boundMatchId: __t.u64(),
  state: __t.string(),
  createdAt: __t.timestamp(),
});
export type Party = __Infer<typeof Party>;

export const PartyMember = __t.object("PartyMember", {
  id: __t.u64(),
  partyId: __t.u64(),
  member: __t.identity(),
  username: __t.string(),
  ready: __t.bool(),
  joinedAt: __t.timestamp(),
});
export type PartyMember = __Infer<typeof PartyMember>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  color: __t.u32(),
  matchId: __t.u64(),
  x: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  state: __t.string(),
  carryingAnchorId: __t.option(__t.u64()),
  lastSeen: __t.timestamp(),
  build: __t.u8(),
  hood: __t.u8(),
  marking: __t.u8(),
  emissiveIntensity: __t.f32(),
  height: __t.f32(),
});
export type Player = __Infer<typeof Player>;

export const Progression = __t.object("Progression", {
  username: __t.string(),
  level: __t.u32(),
  xp: __t.u32(),
  trackTier: __t.u8(),
  updatedAt: __t.timestamp(),
});
export type Progression = __Infer<typeof Progression>;

export const ReportRow = __t.object("ReportRow", {
  username: __t.string(),
  felt: __t.string(),
  truth: __t.string(),
});
export type ReportRow = __Infer<typeof ReportRow>;

export const Tether = __t.object("Tether", {
  id: __t.u64(),
  matchId: __t.u64(),
  absorbed: __t.identity(),
  x: __t.f32(),
  z: __t.f32(),
});
export type Tether = __Infer<typeof Tether>;

export const Unlock = __t.object("Unlock", {
  id: __t.u64(),
  username: __t.string(),
  itemKey: __t.string(),
  source: __t.string(),
  createdAt: __t.timestamp(),
});
export type Unlock = __Infer<typeof Unlock>;

export const Wallet = __t.object("Wallet", {
  username: __t.string(),
  residue: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type Wallet = __Infer<typeof Wallet>;

export const WardenAction = __t.object("WardenAction", {
  id: __t.u64(),
  matchId: __t.u64(),
  actionType: __t.string(),
  target: __t.string(),
  createdAt: __t.timestamp(),
});
export type WardenAction = __Infer<typeof WardenAction>;

export const WardenPresent = __t.object("WardenPresent", {
  id: __t.u8(),
  present: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type WardenPresent = __Infer<typeof WardenPresent>;

export const WardenSeat = __t.object("WardenSeat", {
  matchId: __t.u64(),
  wardenIdentity: __t.identity(),
  lastAction: __t.timestamp(),
});
export type WardenSeat = __Infer<typeof WardenSeat>;

export const WorldEvent = __t.object("WorldEvent", {
  id: __t.u64(),
  matchId: __t.u64(),
  kind: __t.string(),
  x: __t.f32(),
  z: __t.f32(),
  createdAt: __t.timestamp(),
});
export type WorldEvent = __Infer<typeof WorldEvent>;

