// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  energy: __t.f32(),
  phase: __t.u8(),
  manifestCd: __t.f32().name("manifest_cd"),
  wardenIdentity: __t.option(__t.identity()).name("warden_identity"),
  lastActionAt: __t.timestamp().name("last_action_at"),
});
